### ISSUE TITLE
icon change

### ISSUE THREAD

**Issue by TeaqariaWTF** [LemonyOwO/rex-magisk-module#1]
Hi , 

Can we change YouTube and YouTube music icons for Magisk versions?

**Comment by LemonyOwO** [comment]
Not inside the app, but i can try to release versions with different app icons.

**Comment by TeaqariaWTF** [comment]
The YouTube icons I'm using right now are quite nice.

It would be nice to add these icons


![Screenshot_20240318-110635_Ayarlar](https://github.com/LemonyOwO/rex-magisk-module/assets/90970076/c0c69074-c7d0-4573-9700-6dc4b5febb7e)

![Screenshot_20240318-110615_Ayarlar](https://github.com/LemonyOwO/rex-magisk-module/assets/90970076/fb173210-04c5-419a-bbf6-2eddd0ed6910)

**Comment by LemonyOwO** [comment]
I've set the youtube icons to these, if you think of anything else just open a new issue. Thank you for the suggestion!

**Comment by TeaqariaWTF** [comment]
Thank you for your reply.

I wonder if you can also make a work for the opening animation?

For YouTube and music


https://github.com/LemonyOwO/rex-magisk-module/assets/90970076/ba2e98ef-7e7c-4661-b0fc-ce0771c7be56

@LemonyOwO

**Comment by LemonyOwO** [comment]
The custom splash icon animation isn't supported on @anddea's patches.
